on: [push]

name: Rust CI

jobs:
  build_and_test:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
      - name: "Git checkout"
        uses: actions/checkout@v2

      - name: "Rust setup"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "Run Clippy"
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: "cargo test"
        uses: actions-rs/cargo@v1
        with:
          command: test
